# Software example for the appendix of the manuscript.
#
# Evaluates the R code shown in the appendix "Software implementation"
# and writes it, together with its actual output, as an R console
# transcript in a verbatim environment to
#   table_and_figure_manuscript/appendix_software_example.tex
# The manuscript only needs \input{appendix_software_example}, so that
# the code and output printed in the appendix always come from the
# current implementation and are never copied by hand.
#
# Before running this script, set the working directory to a writable
# folder that contains this script.  If the R source files of
# twocpcont are also in that folder, they are used; otherwise the
# installed twocpcont package is used.

# ------------------------------------------------------------
# Load the functions (same convention as the other scripts)
# ------------------------------------------------------------
src_files <- c("GL_nodes_and_weights.R",
               "plackett_gl_full.R",
               "twocpcont_power.R",
               "twocpcont_ss.R",
               "print_twocpcont_ss.R",
               "print_twocpcont_power.R",
               "r_max.R",
               "kappa_star.R")
if (all(file.exists(src_files))) {
  for (f in src_files) source(f)
} else {
  library(twocpcont)
}

output_dir <- "table_and_figure_manuscript"
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}
out_file <- file.path(output_dir, "appendix_software_example.tex")

# ------------------------------------------------------------
# Code shown in the appendix, one element per console input.
# The first element is displayed but not evaluated, because the
# functions have already been loaded above.
# ------------------------------------------------------------
chunks <- c(
  "library(twocpcont)",
  paste0("ss <- twocpcont_ss(delta1 = 1.8, delta2 = 3.1, sd1 = 9, sd2 = 12,\n",
         "                   rho = 0.5, r = 1, alpha = 0.025, beta = 0.13,\n",
         "                   method = \"univariate\")"),
  "ss",
  "ss$n2_cont",
  paste0("twocpcont_power(n1 = ss$n1, n2 = ss$n2, delta1 = 1.8, delta2 = 3.1,\n",
         "                sd1 = 9, sd2 = 12, rho = 0.5, alpha = 0.025)"),
  paste0("sapply(c(0, 0.3, 0.5, 0.8), function(rho) {\n",
         "  twocpcont_ss(delta1 = 1.8, delta2 = 3.1, sd1 = 9, sd2 = 12,\n",
         "               rho = rho, alpha = 0.025, beta = 0.13,\n",
         "               method = \"univariate\")$N\n",
         "})"),
  "kappa <- (3.1 / 12) / (1.8 / 9)",
  "r_max(kappa, alpha = 0.025, beta = 0.13)",
  "kappa_star(epsilon = 0.05, alpha = 0.025, beta = 0.13)"
)

# ------------------------------------------------------------
# Evaluate each chunk and build the console transcript
# ------------------------------------------------------------
old_opts <- options(width = 72, digits = 7)
ex_env <- new.env(parent = globalenv())
transcript <- character(0)
for (i in seq_along(chunks)) {
  code_lines <- strsplit(chunks[i], "\n", fixed = TRUE)[[1]]
  prompts <- c("> ", rep("+ ", length(code_lines) - 1L))
  transcript <- c(transcript, paste0(prompts, code_lines))
  if (i == 1L) next
  out <- utils::capture.output({
    res <- withVisible(eval(parse(text = chunks[i]), envir = ex_env))
    if (res$visible) print(res$value)
  })
  # Drop leading and trailing blank lines produced by the print methods
  while (length(out) > 0L && !nzchar(trimws(out[1L]))) out <- out[-1L]
  while (length(out) > 0L && !nzchar(trimws(out[length(out)]))) {
    out <- out[-length(out)]
  }
  transcript <- c(transcript, out)
}
options(old_opts)

# Guard against lines that would overflow the verbatim block
too_long <- nchar(transcript) > 76L
if (any(too_long)) {
  stop("Transcript lines longer than 76 characters:\n",
       paste(transcript[too_long], collapse = "\n"))
}

tex <- c("% Generated by appendix_software_example.R; do not edit by hand.",
         "{\\small",
         "\\begin{verbatim}",
         transcript,
         "\\end{verbatim}",
         "}")
writeLines(tex, out_file, useBytes = TRUE)
cat(sprintf("Wrote: %s (%d transcript lines)\n", out_file,
            length(transcript)))
