# Copy the tables (.tex) and figures (.pdf, .eps) generated by
# inst/reproduce/create_table_and_figure_manuscript.R into the folder of
# the CSSC manuscript, so that the manuscript always uses the current
# outputs.
#
# Run from the package root (the folder containing DESCRIPTION) after
# the reproduction scripts:
#   source("tools/sync_manuscript_assets.R")

if (!file.exists("DESCRIPTION") ||
    read.dcf("DESCRIPTION", fields = "Package")[1, 1] != "twocpcont") {
  stop("Run this script from the root of the twocpcont package.")
}

src_dir <- file.path("inst", "reproduce", "table_and_figure_manuscript")
dst_dir <- file.path("..", "..", "Manuscript", "CSSC", "Body")
if (!dir.exists(src_dir)) {
  stop("Directory not found: ", src_dir,
       ".  Run the reproduction scripts first.")
}
dir.create(dst_dir, recursive = TRUE, showWarnings = FALSE)

assets <- list.files(src_dir, pattern = "^(table|figure).*\\.(tex|pdf|eps)$",
                     full.names = TRUE)
if (length(assets) == 0L) stop("No tables or figures found in ", src_dir)
ok <- file.copy(assets, dst_dir, overwrite = TRUE)
if (!all(ok)) stop("Failed to copy: ", paste(assets[!ok], collapse = ", "))

dst <- file.path(dst_dir, basename(assets))
same <- unname(tools::md5sum(assets)) == unname(tools::md5sum(dst))
if (!all(same)) {
  stop("Copies differ from sources: ",
       paste(basename(assets)[!same], collapse = ", "))
}
message(sprintf("Copied %d files to %s (all identical).",
                length(assets), normalizePath(dst_dir)))
