# Copy the tables (.tex) and figures (.pdf, .eps) generated by
# inst/reproduce/create_table_and_figure_manuscript.R, and the appendix
# transcript generated by inst/reproduce/appendix_software_example.R,
# into the folders of the CSSC and Pharmaceutical Statistics manuscripts,
# so that the manuscripts always use the current outputs.
#
# Run from the package root (the folder containing DESCRIPTION) after
# the reproduction scripts:
#   source("tools/sync_manuscript_assets.R")

if (!file.exists("DESCRIPTION") ||
    read.dcf("DESCRIPTION", fields = "Package")[1, 1] != "twocpcont") {
  stop("Run this script from the root of the twocpcont package.")
}

src_dir <- file.path("inst", "reproduce", "table_and_figure_manuscript")
if (!dir.exists(src_dir)) {
  stop("Directory not found: ", src_dir,
       ".  Run the reproduction scripts first.")
}

# The CSSC manuscript receives tables, figures (.pdf and .eps) and the
# appendix transcript; the Pharmaceutical Statistics manuscript uses .eps
# figures only.
targets <- list(
  list(dir = file.path("..", "..", "Manuscript", "CSSC", "Body"),
       pattern = "^(table|figure|appendix).*\\.(tex|pdf|eps)$"),
  list(dir = file.path("..", "..", "Manuscript", "Pharmaceutical_Statistics",
                       "Body"),
       pattern = "^(table|figure|appendix).*\\.(tex|eps)$")
)

for (tg in targets) {
  dst_dir <- tg$dir
  dir.create(dst_dir, recursive = TRUE, showWarnings = FALSE)
  assets <- list.files(src_dir, pattern = tg$pattern, full.names = TRUE)
  if (length(assets) == 0L) stop("No tables or figures found in ", src_dir)
  ok <- file.copy(assets, dst_dir, overwrite = TRUE)
  if (!all(ok)) stop("Failed to copy: ", paste(assets[!ok], collapse = ", "))

  dst <- file.path(dst_dir, basename(assets))
  same <- unname(tools::md5sum(assets)) == unname(tools::md5sum(dst))
  if (!all(same)) {
    stop("Copies differ from sources: ",
         paste(basename(assets)[!same], collapse = ", "))
  }
  message(sprintf("Copied %d files to %s (all identical).",
                  length(assets), normalizePath(dst_dir)))
}
